### ISSUE TITLE
Typo in key name

### ISSUE THREAD

**Issue by caderek** [ashubham/w3c-keys#2]
I should probably make a pull request, but don't have time for this now:

`Asterik` should be -> `Asterisk`

If you use VS Code I recommend you use [Code Spell Checker](https://marketplace.visualstudio.com/items?itemName=streetsidesoftware.code-spell-checker) extension to avoid this kind of bugs.

**Comment by ashubham** [comment]
Thanks @caderek for pointing out, fixed in Release 1.0
